### ISSUE TITLE
Pipeline Execution Env. For the Gravitee CICD Orchestrator

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [gravitee-lab/GraviteeCiCdOrchestrator#25]
* fork all git repos of components involved in the test release.json `release-data/apim/1.30.x/tests/release.test4-20-conccurrent.json`
* for all those git repos, add the `.circleci/config.yml`  on all release branches, just pushing a new git commit (no pull request)
* add a `.circleci/config.yml`, in the `release.json` : defined like all gravitee components, except that it will run with git branch filter, filtering all release branches : 

```Yaml
jobs: 
  - release_process: 
    machine:
      image: 'ubuntu-1604:201903-01'    # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
      # resource_class: medium
      # docker_layer_caching: true    # default - false # requires a Circle CI plan that includes [Docker layer caching feature]
    environment:
      DESIRED_DOCKER_TAG: stable-latest
    steps:
      - checkout
      - secrethub/install
      - run:
          name: "Testing local docker installation"
          command: docker version
      - run: # print the name of the branch we're on
          name: "What branch am I on ?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Testing DESIRED_DOCKER_TAG"
          command: echo "Docker tag is [${DESIRED_DOCKER_TAG}]"
      - run: # print the name of the branch we're on
          name: "Docker build"
          command: |
                    pwd
                    ls -allh
                    # docker build --no-cache -t "quay.io/gravitee-lab/cicd-orchestrator:${DESIRED_DOCKER_TAG}" -f ./Dockerfile .
                    docker build -t "quay.io/gravitee-lab/cicd-orchestrator:${DESIRED_DOCKER_TAG}" -f ./Dockerfile .
      - run: # print the name of the branch we're on
          name: "Running the Gio CICD Orchestrator as docker container"
          command: |
                    # checking docker image built in previous step is there
                    docker images
                    # [gravitee-lab/cicd-orchestrator/staging/docker/quay/botuser/username]
                    # and
                    # [gravitee-lab/cicd-orchestrator/staging/docker/quay/botoken/token]
                    # --> are to be set with secrethub cli, and 2 Circle CI Env. Var. have to
                    # be set for [Secrethub CLI Auth], at project, or context level
                    CCI_SECRET_FILE=$PWD/.secrets.json
                    secrethub read  --out-file ${CCI_SECRET_FILE} gravitee-lab/cicd-orchestrator/dev/cci/botuser/.secret.json
                    ls -allh ${CCI_SECRET_FILE}
                    # echo "CICD_BOT_CCI_SECRET=[${CICD_BOT_CCI_SECRET}]"
                    export DOCKER_VOLUMES="-v $PWD/pipeline:/graviteeio/cicd/pipeline -v $PWD/.env:/graviteeio/cicd/.env -v $PWD/.secrets.json:/graviteeio/cicd/.secrets.json"
                    docker run --name orchestrator ${DOCKER_VOLUMES} --restart always -itd quay.io/gravitee-lab/cicd-orchestrator:stable-latest

workflows:
  release_process:
    jobs:
      - build:
          context: gravitee-lab
          filters:
            branches:
              # ---
              # Will run only when git commits are pushed to a release branch
              # Therefore, will be triggered when a pull request, with target branch being 
             # a release branch, is accepted
              only:
                - 1.20.x
                - 1.25.x
                - 1.29.x
                - 1.30.x
                - 3.0.x
                - 3.1.x
```

* run the `gravitee-cicd-orchestrator`, in the https://github.com/gravitee-lab/release  Circle CI Pipeline, as a docker container, with basically : 

```bash
# docker run --name orchestrator -v $PWD/pipeline:/graviteeio/cicd/pipeline -v $PWD/.env:/graviteeio/cicd/.env --restart always --entrypoint /bin/sh -itd quay.io/gravitee-lab/cicd-orchestrator:stable-latest
docker run --name orchestrator -v $PWD/pipeline:/graviteeio/cicd/pipeline -v $PWD/.env:/graviteeio/cicd/.env --restart always -itd quay.io/gravitee-lab/cicd-orchestrator:stable-latest

# and then display logs
docker logs -f orchestrator
```
